### ISSUE TITLE
Passing options don't work?

### ISSUE THREAD

**Issue by MarioHofer** [terinjokes/gulp-uglify#133]
My Gulp uses uglify. Works perfectly, but it seems, that I can't pass any options.

I tried:

.pipe(plug.uglify({mangle: false, compress: false}))

but the output is still compressed and mangled.

Is this a bug or what do I do wrong? Thanks in advance.

**Comment by cwramsey** [comment]
+1 - I'm searching for working examples though so find out if it's a bug or (more likely) just me doing it wrong.

**Comment by terinjokes** [comment]
I'm looking into it to determine if it's a bug, and if it is, from whom.

**Comment by dflynn15** [comment]
Any updates on this? I haven't been able to pass in any options either.

**Comment by terinjokes** [comment]
I haven't found the bug. The options passed to UglifyJS look correct.

**Comment by terinjokes** [comment]
@MarioHofer Can you upload a example project to GitHub?

Also worth noting that `mangle` disables mangling variable names, and `compress` disables some optimizations, but neither disables UglifyJS's behavior of removing whitespace (you can pass a prettify option to `output` for that), and that might be causing the behavior you're seeing.

**Comment by MarioHofer** [comment]
Sorry for the late answere.

I call uglify this way:

```
plug = require('gulp-load-plugins')();
...
.pipe(plug.uglify({mangle: false, compress: false}))
```

The output, this time modernizr starts like this:

```
!function(window,document,undefined){function is(obj,type){return typeof obj===type}function testRunner(){var featureNames,feature,aliasIdx,result,nameIdx,featureName,featureNameSplit;for(var feature
```

Should look different, should it?

**Comment by terinjokes** [comment]
Mario, add `output: { prettify: true }` to your options, and you should get
a pretty printed version.

**Comment by objectkit** [comment]
Just when the guests had gone home, I come along late out of the blue :(  I'm afraid I'm having similar issues, or I'm missing something, or its my configuration (new to Gulp). Forgive the coffee script

````
# Gulpfile extract

uglyOptions =
    beautify: yes
    comments: yes
    sourceMap: no
    mangle: no

gulp.task "build:compress", ->
    gulp.src "./build/tld.vendor.product.edition.js"
        .pipe sourcemaps.init()
        # @see https://www.npmjs.com/package/gulp-uglify
        .pipe uglify uglyOptions
        # This will add .min to a new compressed version of the file
        .pipe rename extname: '.min.js'
        .pipe sourcemaps.write "./"
        .pipe gulp.dest "./build/"
````
when transpiled to JS:
````
var uglyOptions;

uglyOptions = {
  beautify: true,
  comments: true,
  sourceMap: false,
  mangle: false
};

gulp.task("build:compress", function() {
  return gulp.src("./build/tld.vendor.product.edition.js")
    .pipe(sourcemaps.init())
    .pipe(uglify(uglyOptions))
    .pipe(rename({
        extname: '.min.js'
      }))
    .pipe(sourcemaps.write("./")).pipe(gulp.dest("./build/"));
});
````
I understand this segment is out of context of the gulpfile... but am I doing anything wrong? It could be me of course, but regardless of what [options I supply](http://lisperator.net/uglifyjs/codegen), Uglifys output doesn't change- it seems to just use the default settings no matter what. 

gulp 3.9.0 
gulp-uglify 1.5.1

_BTW_, the reason I turned to _sourcemaps_ and _rename_ originally was because the option values I was supplying didn't seem to influence Uglify. Any advice appreciated. I've quickly scanned through this releases source and it seems ok, so its probably me... new to gulp as well... late hours...
