### ISSUE TITLE
File not correctly uglified with gulp-uglify, but correctly with uglify itself

### ISSUE THREAD

**Issue by mthmulders** [terinjokes/gulp-uglify#195]
I have an HTML-file that has a block like this:

    
    <script src="scripts/services/my-service.js"></script>
    

Where `my-service.js` is (comments ommitted):

    (function() {
      'use strict';
      angular.module('app').factory('MyService', function ($filter) {
        var queue = {};
        return {
          push: function (id, promise) {
            if (angular.isUndefined(queue[id])) {
              queue[id] = [];
            }
            if (angular.isArray(promise)) {
              for (var idx = 0; idx < promise.length; idx++) {
                queue[id].push(promise[idx]);
              }
            } else {
              queue[id].push(promise);
            }
            return promise;
          },
        };
      });
    })();

In my `gulpfile.js`, I have (among other stuff):

    var assets = useref({searchPath: ['.', '.tmp']});
    var jsFilter = filter('**/*.js', { restore: true });
    return gulp.src('app/*.html')
        .pipe(assets)
        .pipe(jsFilter)
        .pipe(uglify())
        .pipe(jsFilter.restore)
        .pipe(gulp.dest('../webapp/'))
        .on('error', function(err) {
            console.error('Error in task', err.toString());
        })

Now, if I run gulp, my minified file contains just this:

     !function(){"use strict";angular.module("app").factory("MyService",["$filter",function(n){var r={};return{push:function(n,u){if(angular.isUndefined(r[n])&&(r[n]=[]),angular.isArray(u))for(var e=0;e

It seems to me the file is truncated somewhere in the middle of the `for` loop, but I can't figure out why. I think it's not a bug in uglifyjs itself, since when I run uglifyjs itself (using `node_modules/uglify-js/bin/uglifyjs app/scripts/services/my-service.js --mangle`), I get this:

    (function(){"use strict";angular.module("app").factory("MyService",function(n){var u={};return{push:function(n,r){if(angular.isUndefined(u[n])){u[n]=[]}if(angular.isArray(r)){for(var a=0;a<r.length;a++){u[n].push(r[a])}}else{u[n].push(r)}return r}}})})();

The latter is correct, the former obviously isn't complete and hence is not correct JavaScript. Am I missing something obvious or is something strange going on?

**Comment by terinjokes** [comment]
Thanks for using gulp-uglfiy 💖 !

I've seen problems similar to this before. This happens when Node.js is exiting the process while another thread is writing out the file's content to disk. If you properly register all your asynchronous tasks with gulp, it should prevent this problem.

Check all of your gulp tasks and make sure you're returning a Node.js stream from them, or are calling the callback provided to your task.

I created a document linked from the README, [Why Use Pump?](https://github.com/terinjokes/gulp-uglify/blob/master/docs/why-use-pump/README.md#why-use-pump), that gives reasons for using the `pump` module over using `pipe` directly, such as handling errors at all parts of your pipeline and making it easy to register your stream tasks with gulp properly. You may be interested in rewriting your tasks to use it.

```javascript
gulp.task('minify', function (cb) {
  var assets = useref({searchPath: ['.', '.tmp']});
  var jsFilter = filter('**/*.js', { restore: true });

  pump([
    gulp.src('app/*.html'),
    assets,
    jsFilter,
    uglify(),
    jsFilter.restore,
    gulp.desk('../webapp/')
  ], cb);
});
```
