### ISSUE TITLE
New release with UglifyJS 2.7.5

### ISSUE THREAD

**Issue by steffenweber** [terinjokes/gulp-uglify#261]
First of all, thank you for this Gulp plugin!

I've run into [an issue](https://github.com/mishoo/UglifyJS2/issues/1205) in UglifyJS 2.7.0 that is fixed in UglifyJS 2.7.5. Would it be possible to release a new version that uses UglifyJS 2.7.5?

Alternatively, what about changing the version number in `package.json` from `2.7.x` to `^2.7.x`?

**Comment by terinjokes** [comment]
@steffenweber I'll do a release now. No idea why I didn't get an automated PR from Greenkeeper.

You can always use a different version of UglifyJS, or a fork, by following the [directions in the README](https://github.com/terinjokes/gulp-uglify#using-a-different-uglifyjs).

I don't use ranges for UglifyJS primarily for supportability reasons, otherwise I get a bunch of open issues when UglifyJS has a bad release.

**Comment by steffenweber** [comment]
Thank you! For both the new release and the friendly RTFM notice. :smiley:
